import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const out='dist/studies/01/';
await mkdir(new URL(out,root),{recursive:true});
const art=JSON.parse(await read('content/articles.json')).articles.find(a=>a.id==='horse-time');
const plan=JSON.parse(await read('content/studies/reading-01.json'));
const media=JSON.parse(await read('content/studies/orbit-01.json'));
const bar=(before,after,label)=>`<nav class="study-bar" aria-label="試作比較"><span>STUDY 01 / ${label}</span><a href="${before}">PHASE 04 現行版</a><a href="${after}">試作版</a><a href="/studies/01/life.html#reading-study">本文の試作</a></nav>`;
const enhance=(html,toolbar)=>html.replace('</head>','<meta name="robots" content="noindex"><link rel="stylesheet" href="/studies/01/study.css"></head>').replace(/<body([^>]*)>/,`<body$1>${toolbar}`);
let home=await read('dist/index.html');
home=home.replace(/(href|src)="(?!\/|#|https?:|data:)([^"]+)"/g,'$1="/$2"').replaceAll('"src":"assets/','"src":"/assets/');
// Changes only on the separate study route; the base HOME is never rewritten here.
home=enhance(home,bar('/','/studies/01/index.html','COVER'));
home=home.replaceAll('href="/articles/horse-time.html"','href="/studies/01/life.html"');
home=home.replace('<h2>最近、雨ばっかり。</h2>','<h2><span>最近、</span><span>雨ばっかり。</span></h2>');
const start=home.indexOf('<div class="orbit-field">');
const end=home.indexOf('<div class="orbit-foot">',start);
assert(start>0&&end>start);
const field=`<div class="orbit-field study-orbit"><img class="orbit-original" src="/assets/holos-original.jpg" alt="手仕事の多面体と細い軌道の線を持つHOLOS原本ロゴ" width="1170" height="1084" loading="lazy">${media.map((m,i)=>`<a class="study-object" data-orbit-item="${i}" href="${esc(m.href)}" style="--start:${i}" aria-label="${esc(m.label)} — Collectionへ"><img src="${m.src}" width="160" height="140" alt="${esc(m.title)}" loading="lazy"><span>${m.label}</span></a>`).join('')}</div>`;
home=home.slice(0,start)+field+home.slice(end);
home=home.replace('図版準備中 / 標本名から探索できます。','図版3点 / 試作選定・Public Domain。');
const credits=`<details class="study-credits"><summary>図版の出典・権利 / 試作選定</summary><p>入口のための歴史図版です。HOLOS内の特定標本を描いたものではありません。公開用の選定は未確定です。</p>${media.map(m=>`<p><a href="${m.source_url}">${esc(m.title)}</a><br>${esc(m.creator)} · ${esc(m.date)} · ${esc(m.institution)}<br>${esc(m.credit_line)} · <a href="${m.license}">${m.rights} / CC0</a></p>`).join('')}</details>`;
home=home.replace('</div></section></div><div class="cover-controls"',`</div>${credits}</section></div><div class="cover-controls"`);
home=home.replace('</body>','<script type="module" src="/studies/01/orbit.js"></script></body>');
await writeFile(new URL(out+'index.html',root),home);
let life=await read('dist/articles/horse-time.html');
life=enhance(life,bar('/articles/horse-time.html','/studies/01/life.html','READING'));
const blocks=art.body.slice(0,plan.source_body_end_exclusive);
assert(blocks.every(b=>b.type==='paragraph'));
assert.deepEqual(plan.groups.flat(),blocks.map((_,i)=>i));
const before=blocks.map(b=>`<p>${esc(b.text)}</p>`).join('');
assert(life.includes(before));
const after=`<section id="reading-study" class="reading-study" aria-label="冒頭の段落構成・試作">${plan.groups.map((g,i)=>`<p${plan.intentional_short_groups.includes(i)?' class="timing-line"':''}>${g.map(n=>esc(blocks[n].text)).join('')}</p>`).join('')}</section>`;
life=life.replace(before,after);
await writeFile(new URL(out+'life.html',root),life);
console.log('STUDY 01 built: separate HOME, 12 original blocks → 7 paragraphs; 3 rights-verified archive images.');
